import "@/app/globals.css";
import "mapbox-gl/dist/mapbox-gl.css";

import { theme } from "@/theme";
import {
  Box,
  Container,
  CssBaseline,
  Divider,
  InitColorSchemeScript,
  ThemeProvider,
} from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import HydraAppBar from "@/components/HydraAppBar";
import Footer from "@/components/Footer";
import BackgroundGradient from "@/components/BackgroundGradient";
export const metadata: Metadata = {
  title: "Project Hydra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <InitColorSchemeScript attribute="class" />
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <HydraAppBar />
            <BackgroundGradient />
            <Container
              maxWidth="xl"
              sx={{ width: "100%", mt: 24, minHeight: "100vh", position: "relative", zIndex: 1 }}
            >
              {children}
            </Container>
            <Box sx={{ position: "relative", zIndex: 1 }}>
              <Divider />
              <Footer />
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
